### ISSUE TITLE
Feedback about Edit Family

### ISSUE THREAD

**Issue by eric-pintos** [Tawa/Phoenix#71]
### Issue Description
Recently with my team we were experiencing an issue in which we couldn't import one package from **Family A** into **Family B**. After some time, we realized that **Family B** was set up so that we couldn't import any packages from Family B into it. It was the first time we ran into this flow so it took some time to realize.

In the end, we disabled the rule temporarily, did our changes, and enabled it again. Finding a way to edit it was a bit complex, though.

### Suggestions
- Display the unavailable families on the bottom, and grey them out. If the user wants to import them either way, they get a confirmation pop-up but can do so anyway.
- Adding a more descriptive icon to the Edit Family Feature to improve discoverability. Maybe just a plain button that says "Edit"?

**Comment by Tawa** [comment]
Thank you for your suggestion Eric.

With the release 5.0, the dependencies sheet will display the disabled components with a small message:

<img width="411" alt="image" src="https://github.com/Tawa/Phoenix/assets/29006153/ab78b3ad-e024-43ed-b2d4-77572d8f2cdd">
