### ISSUE TITLE
Resources folder is not created during Generate step

### ISSUE THREAD

**Issue by andressolorzano** [Tawa/Phoenix#76]
We tried to generate the Resources for a package target, seems the ash.json and the package.swift files were updated but the Resources folder wasn't generated so we needed to generate it manually

![Screenshot 2023-11-14 at 16 41 42](https://github.com/Tawa/Phoenix/assets/85230149/823f4a26-af21-4bd5-8fc7-c8a06d98c39e)
![Screenshot 2023-11-14 at 16 42 49](https://github.com/Tawa/Phoenix/assets/85230149/ae9206d7-33a9-4142-8eb8-67ac62ef3d90)

![Screenshot 2023-11-14 at 16 41 36](https://github.com/Tawa/Phoenix/assets/85230149/a709ce23-d8cf-401f-a017-70150925c5e2)

**Comment by Tawa** [comment]
Thank you @andressolorzano for reporting this issue.

This was fixed with this PR: https://github.com/Tawa/Phoenix/pull/77
The fix will be included in update version `5.0.2`.
